### ISSUE TITLE
Can't install SurveySolutionsCOVID19tools

### ISSUE THREAD

**Issue by radyakin** [michael-cw/SurveySolutionsCOVID19tools#1]
I can't install the [SurveySolutionsCOVID19tools](https://github.com/michael-cw/SurveySolutionsCOVID19tools) package following the instructions in the `readme.md` file of this GitHub repository. 

I am getting the following error message:

![image](https://user-images.githubusercontent.com/52933296/191333147-f80a03ef-dad1-466e-aeaa-71b85525d5bf.png)

Is there a problem with the software? or perhaps instructions are not complete? inaccurate?

**Comment by michael-cw** [comment]
No there is no problem with this, however for R beginners some familiarity  with the basic tools & syntax is expected.

More details can be found here: https://www.displayr.com/installing-r-packages-from-github/ (a simple google search like: "how do i install r-package from github" should have gotten you the same result)

In general when learning a new software, it is good practice to familiarize yourself with the basic tools and the working environment, or otherwise ask more experienced colleagues for support.

To also assist users who are not interested in even the most basic requirements in R a new section has been added to the readme.md file.
https://github.com/michael-cw/SurveySolutionsCOVID19tools#for-users-with-absolutely-zero-knowledge-of-r-and-rstudio
